name: CI
on:
  pull_request:

jobs:

  # Python checks
  python_formatting:
    name: Python / Formatting
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          cache-dependency-path: |
            poetry.lock
            poetry.toml
            pyproject.toml
          python-version-file: '.python-version'
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry install -E parsers --sync
      - name: Check formatting
        run: |
          poetry run ruff format . --check
      - name: Check linting
        run: |
          poetry run ruff check . --output-format=github

  python_tests:
    name: Python / Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          cache-dependency-path: |
            poetry.lock
            poetry.toml
            pyproject.toml
          python-version-file: '.python-version'
      - name: Install libxml2-dev and tesseract-ocr
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev tesseract-ocr tesseract-ocr-eng
      - name: Install Poetry dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry install -E parsers --sync
      - name: Run tests
        run: |
          poetry run test
